/* Auto-generated by scripts/generate-airports-reference.ts. Do not edit manually. */

export const AIRPORT_REFERENCE_METADATA = {
  "dataVersion": "2026-03-22-4086",
  "generatedAt": "2026-03-22T09:38:34.865Z",
  "commercialAirportCount": 4086,
  "sourceAirportCount": 84951,
  "sources": {
    "primary": "https://davidmegginson.github.io/ourairports-data/airports.csv",
    "mirror": "https://datahub.io/core/airport-codes/_r/-/archive/data.csv",
    "enrichment": "https://raw.githubusercontent.com/mborsetti/airportsdata/main/airportsdata/airports.csv"
  }
} as const;
