// GENERATED by scripts/generate-example-trip-country-names.mjs — do not edit by hand.
// Run `node scripts/generate-example-trip-country-names.mjs` after changing
// data/countryTravelData.json or the countries used by data/exampleTripCards.ts.
//
// This exists so the homepage example cards can localize a country name without
// dragging data/countryTravelData.json (678 KB) onto the mobile boot path.

const EXAMPLE_TRIP_COUNTRY_NAMES: Record<string, Record<string, string>> = {
  "Portugal": {
    de: "Portugal",
    en: "Portugal",
    es: "Portugal",
    fa: "پرتغال",
    fr: "Portugal",
    it: "Portogallo",
    ko: "포르투갈",
    pl: "Portugalia",
    pt: "Portugal",
    ru: "Португалия",
    ur: "پرتگال",
  },
  "Italy": {
    de: "Italien",
    en: "Italy",
    es: "Italia",
    fa: "ایتالیا",
    fr: "Italie",
    it: "Italia",
    ko: "이탈리아",
    pl: "Włochy",
    pt: "Itália",
    ru: "Италия",
    ur: "اٹلی",
  },
  "Thailand": {
    de: "Thailand",
    en: "Thailand",
    es: "Tailandia",
    fa: "تایلند",
    fr: "Thaïlande",
    it: "Thailandia",
    ko: "태국",
    pl: "Tajlandia",
    pt: "Tailândia",
    ru: "Таиланд",
    ur: "تھائی لینڈ",
  },
  "Cambodia": {
    de: "Kambodscha",
    en: "Cambodia",
    es: "Camboya",
    fa: "کامبوج",
    fr: "Cambodge",
    it: "Cambogia",
    ko: "캄보디아",
    pl: "Kambodża",
    pt: "Camboja",
    ru: "Камбоджа",
    ur: "کمبوڈیا",
  },
  "Vietnam": {
    de: "Vietnam",
    en: "Vietnam",
    es: "Vietnam",
    fa: "ویتنام",
    fr: "Viêt Nam",
    it: "Vietnam",
    ko: "베트남",
    pl: "Wietnam",
    pt: "Vietname",
    ru: "Вьетнам",
    ur: "ویتنام",
  },
  "Laos": {
    de: "Laos",
    en: "Laos",
    es: "Laos",
    fa: "لائوس",
    fr: "Laos",
    it: "Laos",
    ko: "라오스",
    pl: "Laos",
    pt: "Laos",
    ru: "Лаос",
    ur: "لاؤس",
  },
  "Japan": {
    de: "Japan",
    en: "Japan",
    es: "Japón",
    fa: "ژاپن",
    fr: "Japon",
    it: "Giappone",
    ko: "일본",
    pl: "Japonia",
    pt: "Japão",
    ru: "Япония",
    ur: "جاپان",
  },
  "Peru": {
    de: "Peru",
    en: "Peru",
    es: "Perú",
    fa: "پرو",
    fr: "Pérou",
    it: "Perù",
    ko: "페루",
    pl: "Peru",
    pt: "Peru",
    ru: "Перу",
    ur: "پیرو",
  },
  "New Zealand": {
    de: "Neuseeland",
    en: "New Zealand",
    es: "Nueva Zelanda",
    fa: "نیوزیلند",
    fr: "Nouvelle-Zélande",
    it: "Nuova Zelanda",
    ko: "뉴질랜드",
    pl: "Nowa Zelandia",
    pt: "Nova Zelândia",
    ru: "Новая Зеландия",
    ur: "نیوزی لینڈ",
  },
  "Morocco": {
    de: "Marokko",
    en: "Morocco",
    es: "Marruecos",
    fa: "مراکش",
    fr: "Maroc",
    it: "Marocco",
    ko: "모로코",
    pl: "Maroko",
    pt: "Marrocos",
    ru: "Марокко",
    ur: "مراکش",
  },
  "Iceland": {
    de: "Island",
    en: "Iceland",
    es: "Islandia",
    fa: "ایسلند",
    fr: "Islande",
    it: "Islanda",
    ko: "아이슬란드",
    pl: "Islandia",
    pt: "Islândia",
    ru: "Исландия",
    ur: "آئس لینڈ",
  },
};

/**
 * Localized display name for a country used by an example trip card. Falls back
 * to the English name the card carries, so an unknown country still renders.
 */
export const getExampleTripCountryDisplayName = (englishName: string, locale?: string): string => {
  const trimmed = englishName.trim();
  const names = EXAMPLE_TRIP_COUNTRY_NAMES[trimmed];
  if (!names) return trimmed;

  const localeKey = (locale || 'en').trim().toLowerCase().split('-')[0] || 'en';
  return names[localeKey] || names.en || trimmed;
};
