import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import path from 'node:path';

const FLAG_SVG_FILE_REGEX = /^[a-z0-9-]+\.svg$/i;

export interface FlagpackSyncResult {
  total: number;
  copied: number;
  removed: number;
  files: string[];
}

const compareFileContent = (leftPath: string, rightPath: string): boolean => {
  const left = readFileSync(leftPath);
  const right = readFileSync(rightPath);
  return left.length === right.length && left.equals(right);
};

export const listFlagSvgFiles = (directory: string): string[] => {
  if (!existsSync(directory)) return [];

  return readdirSync(directory)
    .filter((fileName) => FLAG_SVG_FILE_REGEX.test(fileName))
    .sort((left, right) => left.localeCompare(right));
};

export const syncFlagpack4x3Assets = (sourceDir: string, targetDir: string): FlagpackSyncResult => {
  if (!existsSync(sourceDir)) {
    throw new Error(`Flag source directory does not exist: ${sourceDir}`);
  }

  mkdirSync(targetDir, { recursive: true });

  const sourceFiles = listFlagSvgFiles(sourceDir);
  if (sourceFiles.length === 0) {
    throw new Error(`No flag SVG files found in ${sourceDir}`);
  }

  const sourceFileSet = new Set(sourceFiles);
  let copied = 0;

  for (const fileName of sourceFiles) {
    const sourcePath = path.join(sourceDir, fileName);
    const targetPath = path.join(targetDir, fileName);

    const shouldCopy = !existsSync(targetPath) || !compareFileContent(sourcePath, targetPath);
    if (!shouldCopy) continue;

    copyFileSync(sourcePath, targetPath);
    copied += 1;
  }

  const targetFiles = listFlagSvgFiles(targetDir);
  let removed = 0;

  for (const fileName of targetFiles) {
    if (sourceFileSet.has(fileName)) continue;
    rmSync(path.join(targetDir, fileName), { force: true });
    removed += 1;
  }

  return {
    total: sourceFiles.length,
    copied,
    removed,
    files: sourceFiles,
  };
};

const toFlagCode = (fileName: string): string | null => {
  if (!FLAG_SVG_FILE_REGEX.test(fileName)) return null;
  return fileName.replace(/\.svg$/i, '').toLowerCase();
};

export const buildFlagpackCss = (flagFiles: string[]): string => {
  const sortedCodes = Array.from(
    new Set(
      flagFiles
        .map(toFlagCode)
        .filter((value): value is string => Boolean(value))
        .sort((left, right) => left.localeCompare(right)),
    ),
  );

  const codeRules = sortedCodes.map((code) => `.${code}{background-image:url("/flags/4x3/${code}.svg")}`);

  return [
    '/* Auto-generated by scripts/sync-flagpack-assets.ts */',
    '.fp{position:relative;display:inline-block;background-size:auto 100%;background-position:center;background-repeat:no-repeat}',
    '.fp:before{content:"\\00a0"}',
    '.fp{line-height:1em;width:1.33333em}',
    '.fp.fp-square{line-height:1em;width:1em}',
    '.fp.fp-rounded{border-radius:.16667em}',
    '.fp.fp-md{line-height:1.5em;width:2em}',
    '.fp.fp-md.fp-square{line-height:1.5em;width:1.5em}',
    '.fp.fp-md.fp-rounded{border-radius:.25em}',
    '.fp.fp-lg{line-height:2em;width:2.66667em}',
    '.fp.fp-lg.fp-square{line-height:2em;width:2em}',
    '.fp.fp-lg.fp-rounded{border-radius:.25em}',
    ...codeRules,
    '',
  ].join('\n');
};
