import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  buildDataVersion,
  ENRICHMENT_AIRPORTS_URL,
  generateAirportReferenceArtifacts,
  mergeAirportSources,
  MIRROR_AIRPORTS_URL,
  parseCsvLine,
  parseEnrichmentAirportCsv,
  parsePrimaryAirportCsv,
  PRIMARY_AIRPORTS_URL,
  resolveCountryName,
} from '../shared/airportReferenceCatalog';
import type { AirportReference, AirportReferenceMetadata } from '../shared/airportReference';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '..');
const AIRPORTS_DATA_DIR = resolve(REPO_ROOT, 'data/airports');
const AIRPORTS_DATA_OUTPUT_PATH = resolve(AIRPORTS_DATA_DIR, 'commercialAirports.generated.ts');
const AIRPORTS_METADATA_OUTPUT_PATH = resolve(AIRPORTS_DATA_DIR, 'metadata.generated.ts');
const AIRPORTS_SQL_OUTPUT_PATH = resolve(REPO_ROOT, 'docs/airport-reference.seed.generated.sql');
const PUBLIC_AIRPORTS_DATA_DIR = resolve(REPO_ROOT, 'public/data/airports');
const PUBLIC_AIRPORTS_JSON_OUTPUT_PATH = resolve(PUBLIC_AIRPORTS_DATA_DIR, 'commercialAirports.generated.json');
const PUBLIC_AIRPORTS_METADATA_JSON_OUTPUT_PATH = resolve(PUBLIC_AIRPORTS_DATA_DIR, 'metadata.generated.json');

const AUTO_GENERATED_COMMENT = '/* Auto-generated by scripts/generate-airports-reference.ts. Do not edit manually. */';

const escapeSqlString = (value: string): string => value.replace(/'/g, "''");

const toSqlString = (value: string | null): string => (
  value === null ? 'null' : `'${escapeSqlString(value)}'`
);

const toSqlNumber = (value: number): string => (
  Number.isFinite(value) ? String(value) : 'null'
);

const serializeCompactJsonArray = <T>(items: T[]): string => {
  if (items.length === 0) return '[]';
  return `[\n${items.map((item) => JSON.stringify(item)).join(',\n')}\n]`;
};

const serializeAirportsModule = (airports: AirportReference[]): string => (
  `${AUTO_GENERATED_COMMENT}

export const COMMERCIAL_AIRPORT_REFERENCES = ${serializeCompactJsonArray(airports)} as const;
`
);

const serializeMetadataModule = (metadata: AirportReferenceMetadata): string => (
  `${AUTO_GENERATED_COMMENT}

export const AIRPORT_REFERENCE_METADATA = ${JSON.stringify(metadata, null, 2)} as const;
`
);

const serializeAirportsJson = (airports: AirportReference[]): string => JSON.stringify(airports);

const serializeMetadataJson = (metadata: AirportReferenceMetadata): string => JSON.stringify(metadata);

export const serializeAirportSeedSql = (
  airports: AirportReference[],
  metadata: AirportReferenceMetadata,
): string => {
  const rows = airports.map((airport) => `(${[
    toSqlString(airport.ident),
    toSqlString(airport.iataCode),
    toSqlString(airport.icaoCode),
    toSqlString(airport.name),
    toSqlString(airport.municipality),
    toSqlString(airport.subdivisionName),
    toSqlString(airport.regionCode),
    toSqlString(airport.countryCode),
    toSqlString(airport.countryName),
    toSqlNumber(airport.latitude),
    toSqlNumber(airport.longitude),
    toSqlString(airport.timezone),
    toSqlString(airport.airportType),
    airport.scheduledService ? 'true' : 'false',
    airport.isCommercial ? 'true' : 'false',
    toSqlString(airport.commercialServiceTier),
    airport.isMajorCommercial ? 'true' : 'false',
  ].join(', ')})`);

  return `-- Generated from scripts/generate-airports-reference.ts
-- Do not edit manually.

begin;

delete from public.airports_reference_metadata;
delete from public.airports_reference;

insert into public.airports_reference (
  ident,
  iata_code,
  icao_code,
  name,
  municipality,
  subdivision_name,
  region_code,
  country_code,
  country_name,
  latitude,
  longitude,
  timezone,
  airport_type,
  scheduled_service,
  is_commercial,
  commercial_service_tier,
  is_major_commercial
)
values
${rows.join(',\n')}
;

insert into public.airports_reference_metadata (
  id,
  data_version,
  generated_at,
  commercial_airport_count,
  source_airport_count,
  sources,
  synced_at,
  synced_by
)
values (
  'global',
  ${toSqlString(metadata.dataVersion)},
  ${toSqlString(metadata.generatedAt)},
  ${toSqlNumber(metadata.commercialAirportCount)},
  ${toSqlNumber(metadata.sourceAirportCount)},
  '${escapeSqlString(JSON.stringify(metadata.sources))}'::jsonb,
  now(),
  'seed.generated.sql'
)
on conflict (id) do update set
  data_version = excluded.data_version,
  generated_at = excluded.generated_at,
  commercial_airport_count = excluded.commercial_airport_count,
  source_airport_count = excluded.source_airport_count,
  sources = excluded.sources,
  synced_at = excluded.synced_at,
  synced_by = excluded.synced_by
;

commit;
`;
};

const writeArtifacts = async (): Promise<void> => {
  const { airports, metadata } = await generateAirportReferenceArtifacts();

  await mkdir(AIRPORTS_DATA_DIR, { recursive: true });
  await mkdir(PUBLIC_AIRPORTS_DATA_DIR, { recursive: true });
  await writeFile(AIRPORTS_DATA_OUTPUT_PATH, serializeAirportsModule(airports), 'utf8');
  await writeFile(AIRPORTS_METADATA_OUTPUT_PATH, serializeMetadataModule(metadata), 'utf8');
  await writeFile(AIRPORTS_SQL_OUTPUT_PATH, serializeAirportSeedSql(airports, metadata), 'utf8');
  await writeFile(PUBLIC_AIRPORTS_JSON_OUTPUT_PATH, serializeAirportsJson(airports), 'utf8');
  await writeFile(PUBLIC_AIRPORTS_METADATA_JSON_OUTPUT_PATH, serializeMetadataJson(metadata), 'utf8');

  console.log(
    `Wrote ${airports.length} commercial airports to ${AIRPORTS_DATA_OUTPUT_PATH.replace(`${REPO_ROOT}/`, '')}, ${PUBLIC_AIRPORTS_JSON_OUTPUT_PATH.replace(`${REPO_ROOT}/`, '')}, and ${AIRPORTS_SQL_OUTPUT_PATH.replace(`${REPO_ROOT}/`, '')}.`
  );
};

if (import.meta.url === new URL(process.argv[1], 'file://').toString()) {
  void writeArtifacts();
}

export const __airportGenerationInternals = {
  buildDataVersion,
  parseCsvLine,
  parsePrimaryAirportCsv,
  parseEnrichmentAirportCsv,
  mergeAirportSources,
  resolveCountryName,
  serializeAirportSeedSql,
  PRIMARY_AIRPORTS_URL,
  MIRROR_AIRPORTS_URL,
  ENRICHMENT_AIRPORTS_URL,
};
